engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: false
  csslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
