engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-2"
  csslint:
    enabled: true
  fixme:
    enabled: true
  shellcheck:
    enabled: true
  markdownlint:
    enabled: true
